spring:
  application:
    name: logindemo
  datasource:
    url: jdbc:mysql://localhost:3306/logindemo_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name=com: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect